
; SND
; ----------------------------------------------------------------------------


CFREG0	.EQU	CFBASE+0	; DATA PORT
CFREG1	.EQU	CFBASE+1	; READ: ERROR CODE, WRITE: FEATURE
CFREG2	.EQU	CFBASE+2	; NUMBER OF SECTORS TO TRANSFER
CFREG3	.EQU	CFBASE+3	; SECTOR ADDRESS LBA 0 [0:7]
CFREG4	.EQU	CFBASE+4	; SECTOR ADDRESS LBA 1 [8:15]
CFREG5	.EQU	CFBASE+5	; SECTOR ADDRESS LBA 2 [16:23]
CFREG6	.EQU	CFBASE+6	; SECTOR ADDRESS LBA 3 [24:27 (LSB)]
CFREG7	.EQU	CFBASE+7	; READ: STATUS, WRITE: COMMAND